### ISSUE TITLE
`awatch` on windows can't be killed with Ctrl+C

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/watchfiles#110]
The "KeyboardInterrupt" gets logged but the process doesn't terminate until the next file system event happens and `RustNotify.watch()` returns.

This is because windows doesn't have signals, so `open_signal_receiver`

https://github.com/samuelcolvin/watchfiles/blob/7a74df9d1a403fcf57e9b27ac65cfb30c2dbf8c9/watchfiles/main.py#L181

Doesn't work and there's no way to tell the rust code to terminate.

Potential solution is to return from `RustNotify.watch()` regularly, and thereby check if an error has been raised. Seems a bit ugly but I can't think of a better solution.

Let's see if people actually suffer from this?

**Comment by TBBle** [comment]
I just came across this older bug, and I'm trying to wrap my head around it: `SIGINT` _does_ work on Windows (but won't interrupt the thread's blocking API call, AFAIK), and AFAIK the call to `PyErr_CheckSignals` (`py.check_signals()` in this codebase) done each `step`  _should_ have triggered a `KeyboardInterrupt` in the main thread when it was called. The fact that a `KeyboardInterrupt` was seen says that `SIGINT` was called, as that is done by python's default `SIGINT` handler in Python code.

I do wonder if `PyErr_CheckSignals` called on a thread doesn't raise an error on Windows if the signal's already been handled on the main thread? But the `stop_event` should have been set and hence terminated the loop in the next step if that was the case. So I'm somewhat mystified here.

**Comment by samuelcolvin** [comment]
Does sound mystifying. I don't have windows and your logic makes sense, so I don't know what to suggest.

**Comment by TBBle** [comment]
Fair 'nuff. I haven't tested my app directly on Windows, since we're running it inside a container. If I have some spare time, I'll have a play with it when I'm looking into the double-`KeyboardInterrupt` weirdness.

**Comment by samuelcolvin** [comment]
When I tested it on a VM on Ubuntu it seemed it to work. The stop_event didn't work, but the exception propagated on the next return from the rust code.

But I might have missed something.

**Comment by TBBle** [comment]
Hmm. I noticed [the comment added more-recently](https://github.com/samuelcolvin/watchfiles/blob/main/watchfiles/main.py#L217), and it does indeed appear that `asyncio.add_signal_handler` doesn't work on Windows, although there's no clear indication why, since the only Unix-only API it calls is already in that state on Windows, and e.g., `signal.signal` _is_ supported on Windows.

So yeah, the original issue description was give-or-take correct, `anyio.open_signal_receiver` doesn't work because `asyncio.add_signal_handler` is not implemented on Windows, rather than lack of signals at all.

**Comment by samuelcolvin** [comment]
Also worth checking #136 to see if that makes it better or worse

**Comment by TBBle** [comment]
Oh, interesting, the changes in #136 look like they are very similar to what I did to avoid the double-`KeyboardInterrupt`, by catching the cancelation of the awaited task, and setting my own `stop_event` if I saw it. Looking at https://github.com/samuelcolvin/watchfiles/issues/128#issuecomment-1109711265, that looks like roughly the same double-`KeyboardInterrupt` issue I saw.

So I'll follow up on that part of it in #128 if I come back to it, and for the actual topic of this bug, it looks like it's an `asyncio` deficiency that'll be hard to work around.

**Comment by Luiz-Monad** [comment]
Using an Event seems like the way to do it. https://github.com/ThomasMonkman/filewatch/blob/a59891baf375b73ff28144973a6fafd3fe40aa21/FileWatch.hpp#L330

Windows has IOCP, which is IO completion ports which can do OVERLAPPED I/O.
I'm mystified python doesn't provide a signaling implementation using events. 
And you can cancel I/O on Windows using that if you start them as Async.

One would presume "async" I/O uses actual asynchronous APIs from the operating system instead of a separate thread, I guess its some python limitation.
